name: $(SourceBranchName)_0.1_$(Date:yyMM)$(DayOfMonth).$(Rev:r)

trigger:
  - main

variables:
  # Agent VM image name
  vmImageName: 'windows-2019'
  
stages:
- stage: Bundle
  displayName: Bundle stage

  jobs:
  - job: Bundle
    displayName: Bundle
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 16.15.1'
      inputs:
        versionSpec: 16.15.1
    - task: Npm@1
      displayName: 'npm ci'
      inputs:
        command: custom
        verbose: false
        customCommand: 'ci'
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run build'
    - task: ArchiveFiles@2
      displayName: 'Archive dist folder'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)-build.zip'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts: drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Bundle
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/**/*.zip'
              destinationFolder: '$(System.DefaultWorkingDirectory)/build'
          - task: AzureFileCopy@4
            displayName: 'Azure File Copy'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/build/*'
              azureSubscription: 'Visual Studio Enterprise – MPN (31c30357-3d5e-4c0f-a82b-2283d0db4312)'
              Destination: AzureBlob
              storage: jsontemplates
              ContainerName: '$web'
          # - task: AzureCLI@1
          #   displayName: 'Azure CLI '
          #   inputs:
          #     azureSubscription: 'Visual Studio Enterprise – MPN (31c30357-3d5e-4c0f-a82b-2283d0db4312)'
          #     scriptLocation: inlineScript
          #     inlineScript: 'az cdn endpoint purge --resource-group AzureRedirect --profile-name redirect-content --name redirect-content --content-paths /*'
